version: '3.8'

# This is like `docker-compose.yml` except it just sets up a database without running
# the api and the app. Those are meant to be launched on bare metal when developing

services:
  pgadmin:
    image: docker.io/dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin:/var/lib/pgadmin
    
  db:
    image: docker.io/postgres:alpine3.18
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      # In the dev version, the port is exposed, because in the prod version, you can
      # access the db by just using its docker container name
      - "8001:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgadmin:
